"""Primeira migration

Revision ID: 0001
Revises: 
Create Date: 2023-09-25 18:18:45.261147

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("create schema auth")
    op.execute("create schema icatu")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "funcoes",
        sa.Column("id", sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column("nome", sa.TEXT(), nullable=False),
        sa.Column("funcao_acima_id", sa.SmallInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["funcao_acima_id"],
            ["auth.funcoes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nome"),
        sa.UniqueConstraint("nome"),
        schema="auth",
    )
    op.create_table(
        "usuarios",
        sa.Column("id", sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column("nome", sa.TEXT(), nullable=False),
        sa.Column("email", sa.TEXT(), nullable=False),
        sa.Column(
            "senha",
            sa.TEXT(),
            server_default="$argon2id$v=19$m=65536,t=3,p=4$b7wXYBsd7CcXxmyVOLlYQQ$3ydt9HCd38DTdOtziaDL77cMllCZ19BnI97rWfmiOwM",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("email"),
        schema="auth",
    )
    op.create_table(
        "dispositivos",
        sa.Column("id", sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column("agente", sa.TEXT(), nullable=False),
        sa.Column("endereco", sa.TEXT(), nullable=False),
        sa.Column("ultima_atividade", sa.TIMESTAMP(), nullable=False),
        sa.Column("data_login", sa.TIMESTAMP(), nullable=False),
        sa.Column("token", sa.CHAR(length=64), nullable=False),
        sa.Column("localizacao", sa.TEXT(), nullable=True),
        sa.Column("usuario_id", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["auth.usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
        sa.UniqueConstraint("token"),
        schema="auth",
    )
    op.create_table(
        "usuarios_funcoes",
        sa.Column("usuario_id", sa.SmallInteger(), nullable=False),
        sa.Column("funcao_id", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["funcao_id"],
            ["auth.funcoes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["auth.usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("usuario_id", "funcao_id"),
        schema="auth",
    )
    op.create_table(
        "analistas_credito",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("user_id", sa.SmallInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
        schema="icatu",
    )
    op.create_table(
        "ativo_fluxo_tipos",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.Column("tokens", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nome"),
        schema="icatu",
    )
    op.create_table(
        "ativo_indices",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nome"),
        schema="icatu",
    )
    op.create_table(
        "ativo_tipos",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nome"),
        schema="icatu",
    )
    op.create_table(
        "emissor_grupos",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nome"),
        schema="icatu",
    )
    op.create_table(
        "emissor_setores",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nome"),
        schema="icatu",
    )
    op.create_table(
        "fundo_classificacoes",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("nome", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nome"),
        schema="icatu",
    )
    op.create_table(
        "fundo_custodiantes",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("nome", sa.TEXT(), nullable=False),
        sa.Column("nome_curto", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nome"),
        sa.UniqueConstraint("nome_curto"),
        schema="icatu",
    )
    op.create_table(
        "fundo_indices",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("nome", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nome"),
        schema="icatu",
    )
    op.create_table(
        "fundo_riscos",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("nome", sa.CHAR(length=2), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nome"),
        schema="icatu",
    )
    op.create_table(
        "fundo_tipos",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("nome", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nome"),
        schema="icatu",
    )
    op.create_table(
        "historico_cdi",
        sa.Column("data", sa.Date(), nullable=False),
        sa.Column("taxa", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("indice_acumulado", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("atualizacao", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("data"),
        schema="icatu",
    )
    op.create_table(
        "historico_igpm",
        sa.Column("data", sa.Date(), nullable=False),
        sa.Column("indice_acumulado", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("atualizacao", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("data"),
        schema="icatu",
    )
    op.create_table(
        "historico_ipca",
        sa.Column("data", sa.Date(), nullable=False),
        sa.Column("indice_acumulado", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("atualizacao", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("data"),
        schema="icatu",
    )
    op.create_table(
        "igpm_proj",
        sa.Column("data", sa.Date(), nullable=False),
        sa.Column("projetado", sa.Boolean(), nullable=False),
        sa.Column("taxa", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("atualizacao", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("data"),
        schema="icatu",
    )
    op.create_table(
        "ipca_proj",
        sa.Column("data", sa.Date(), nullable=False),
        sa.Column("projetado", sa.Boolean(), nullable=False),
        sa.Column("taxa", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("atualizacao", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("data"),
        schema="icatu",
    )
    op.create_table(
        "rotina",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="icatu",
    )
    op.create_table(
        "taxas_dap",
        sa.Column("data_referencia", sa.Date(), nullable=False),
        sa.Column("data_vencimento", sa.Date(), nullable=False),
        sa.Column("taxa", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("data_referencia", "data_vencimento"),
        sa.UniqueConstraint(
            "data_referencia",
            "data_vencimento",
            name="taxas_dap_data_referencia_data_vencimento_unique",
        ),
        schema="icatu",
    )
    op.create_table(
        "taxas_di",
        sa.Column("data", sa.Date(), nullable=False),
        sa.Column("dias_corridos", sa.Integer(), nullable=False),
        sa.Column("taxa", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.PrimaryKeyConstraint("data", "dias_corridos"),
        sa.UniqueConstraint(
            "data", "dias_corridos", name="taxas_di_data_dias_corridos_unique"
        ),
        schema="icatu",
    )
    op.create_table(
        "taxas_ntnb",
        sa.Column("data_referencia", sa.Date(), nullable=False),
        sa.Column("data_vencimento", sa.Date(), nullable=False),
        sa.Column("taxa", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("duration", sa.DOUBLE_PRECISION(), nullable=False),
        sa.PrimaryKeyConstraint("data_referencia", "data_vencimento"),
        sa.UniqueConstraint(
            "data_referencia",
            "data_vencimento",
            name="taxas_ntnb_data_referencia_data_vencimento_unique",
        ),
        schema="icatu",
    )
    op.create_table(
        "atualizacao_rotina",
        sa.Column("id_rotina", sa.Integer(), nullable=False),
        sa.Column("data", sa.Date(), nullable=False),
        sa.Column("atualizacao", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_rotina"],
            ["icatu.rotina.id"],
        ),
        sa.PrimaryKeyConstraint("id_rotina", "data"),
        sa.UniqueConstraint(
            "id_rotina", "data", name="atualizacao_rotina_id_rotina_data_unique"
        ),
        schema="icatu",
    )
    op.create_table(
        "emissores",
        sa.Column("cnpj", sa.CHAR(length=14), nullable=False),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.Column("grupo_id", sa.SmallInteger(), nullable=True),
        sa.Column("setor_id", sa.SmallInteger(), nullable=True),
        sa.Column("analista_credito_id", sa.SmallInteger(), nullable=True),
        sa.Column("codigo_cvm", sa.Integer(), nullable=True),
        sa.Column("tier", sa.SmallInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["analista_credito_id"],
            ["icatu.analistas_credito.id"],
        ),
        sa.ForeignKeyConstraint(
            ["grupo_id"],
            ["icatu.emissor_grupos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["setor_id"],
            ["icatu.emissor_setores.id"],
        ),
        sa.PrimaryKeyConstraint("cnpj"),
        sa.UniqueConstraint("nome"),
        schema="icatu",
    )
    op.create_table(
        "fundos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("isin", sa.CHAR(length=12), nullable=False),
        sa.Column("nome", sa.TEXT(), nullable=False),
        sa.Column("codigo_brit", sa.Integer(), nullable=False),
        sa.Column("cnpj", sa.CHAR(length=14), nullable=False),
        sa.Column("atualizacao", sa.TIMESTAMP(), nullable=False),
        sa.Column("conta_cetip", sa.TEXT(), nullable=True),
        sa.Column("pl_alocavel", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("codigo_carteira", sa.TEXT(), nullable=True),
        sa.Column("indice_id", sa.SmallInteger(), nullable=False),
        sa.Column("tipo_id", sa.SmallInteger(), nullable=False),
        sa.Column("risco_id", sa.SmallInteger(), nullable=False),
        sa.Column("classificacao_id", sa.SmallInteger(), nullable=False),
        sa.Column("custodiante_id", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["classificacao_id"],
            ["icatu.fundo_classificacoes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["custodiante_id"],
            ["icatu.fundo_custodiantes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["indice_id"],
            ["icatu.fundo_indices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["risco_id"],
            ["icatu.fundo_riscos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tipo_id"],
            ["icatu.fundo_tipos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cnpj"),
        sa.UniqueConstraint("codigo_brit"),
        schema="icatu",
    )
    op.create_index(
        op.f("ix_icatu_fundos_isin"), "fundos", ["isin"], unique=True, schema="icatu"
    )
    op.create_table(
        "ativos",
        sa.Column("codigo", sa.VARCHAR(length=11), nullable=False),
        sa.Column("valor_emissao", sa.Double(), nullable=False),
        sa.Column("data_emissao", sa.Date(), nullable=False),
        sa.Column("inicio_rentabilidade", sa.Date(), nullable=False),
        sa.Column("data_vencimento", sa.Date(), nullable=False),
        sa.Column("taxa", sa.Double(), nullable=False),
        sa.Column("atualizacao", sa.DateTime(), nullable=False),
        sa.Column("cadastro_manual", sa.Boolean(), nullable=False),
        sa.Column("emissor_cnpj", sa.CHAR(length=14), nullable=False),
        sa.Column("tipo_id", sa.SmallInteger(), nullable=False),
        sa.Column("indice_id", sa.SmallInteger(), nullable=False),
        sa.Column("apelido", sa.Text(), nullable=True),
        sa.Column("isin", sa.VARCHAR(length=12), nullable=True),
        sa.Column("serie", sa.SmallInteger(), nullable=True),
        sa.Column("emissao", sa.SmallInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["emissor_cnpj"],
            ["icatu.emissores.cnpj"],
        ),
        sa.ForeignKeyConstraint(
            ["indice_id"],
            ["icatu.ativo_indices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tipo_id"],
            ["icatu.ativo_tipos.id"],
        ),
        sa.PrimaryKeyConstraint("codigo"),
        schema="icatu",
    )
    op.create_table(
        "ativo_fluxos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ativo_codigo", sa.VARCHAR(length=11), nullable=False),
        sa.Column("data_pagamento", sa.Date(), nullable=False),
        sa.Column("ativo_fluxo_tipo_id", sa.SmallInteger(), nullable=False),
        sa.Column("data_evento", sa.Date(), nullable=True),
        sa.Column("percentual", sa.Double(), nullable=True),
        sa.Column("pu_evento", sa.Double(), nullable=True),
        sa.Column("pu_calculado", sa.Double(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ativo_codigo"],
            ["icatu.ativos.codigo"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ativo_fluxo_tipo_id"],
            ["icatu.ativo_fluxo_tipos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "ativo_codigo",
            "data_pagamento",
            "ativo_fluxo_tipo_id",
            name="codigo_pagamento_tipo_unique",
        ),
        schema="icatu",
    )
    op.create_table(
        "ativos_ipca",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mesversario", sa.Integer(), nullable=False),
        sa.Column("ipca_negativo", sa.Boolean(), nullable=False),
        sa.Column("ipca_2_meses", sa.Boolean(), nullable=False),
        sa.Column("ativo_codigo", sa.VARCHAR(length=11), nullable=False),
        sa.ForeignKeyConstraint(
            ["ativo_codigo"],
            ["icatu.ativos.codigo"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ativo_codigo"),
        schema="icatu",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ativos_ipca", schema="icatu")
    op.drop_table("ativo_fluxos", schema="icatu")
    op.drop_table("ativos", schema="icatu")
    op.drop_index(op.f("ix_icatu_fundos_isin"), table_name="fundos", schema="icatu")
    op.drop_table("fundos", schema="icatu")
    op.drop_table("emissores", schema="icatu")
    op.drop_table("atualizacao_rotina", schema="icatu")
    op.drop_table("taxas_ntnb", schema="icatu")
    op.drop_table("taxas_di", schema="icatu")
    op.drop_table("taxas_dap", schema="icatu")
    op.drop_table("rotina", schema="icatu")
    op.drop_table("ipca_proj", schema="icatu")
    op.drop_table("igpm_proj", schema="icatu")
    op.drop_table("historico_ipca", schema="icatu")
    op.drop_table("historico_igpm", schema="icatu")
    op.drop_table("historico_cdi", schema="icatu")
    op.drop_table("fundo_tipos", schema="icatu")
    op.drop_table("fundo_riscos", schema="icatu")
    op.drop_table("fundo_indices", schema="icatu")
    op.drop_table("fundo_custodiantes", schema="icatu")
    op.drop_table("fundo_classificacoes", schema="icatu")
    op.drop_table("emissor_setores", schema="icatu")
    op.drop_table("emissor_grupos", schema="icatu")
    op.drop_table("ativo_tipos", schema="icatu")
    op.drop_table("ativo_indices", schema="icatu")
    op.drop_table("ativo_fluxo_tipos", schema="icatu")
    op.drop_table("analistas_credito", schema="icatu")
    op.drop_table("usuarios_funcoes", schema="auth")
    op.drop_table("dispositivos", schema="auth")
    op.drop_table("usuarios", schema="auth")
    op.drop_table("funcoes", schema="auth")
    # ### end Alembic commands ###

    op.execute("drop schema icatu")
    op.execute("drop schema auth")
