"""Ajustes ativos: Agentes fiduciários

Revision ID: 0006
Revises: 0005
Create Date: 2024-01-26 17:11:24.826900

"""
from typing import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        create table icatu.agentes_fiduciarios (
            id serial4 primary key,
            nome text NOT NULL,
            tokens text NOT NULL
        )
        """
    )
    op.execute(
        """
        insert into icatu.agentes_fiduciarios
            (id, nome, tokens)
        values
            (1,'ABILIO MACHADO NETO','ABILIO MACHADO NETO,ABILIO MACHADO NETO'),
            (2,'AFONSO GLICERIO C. M. NETO','AFONSO GLICERIO C M NETO,AFONSO GLICERIO C. M. NETO'),
            (3,'AGENDA CCTVM LTDA.','AGENDA,AGENDA CCTVM LTDA.'),
            (4,'ALBERTO EUSEBIO CARMO TANGARI','ALBERTO EUSEBIO CARMO TANGARI,ALBERTO EUSEBIO CARMO TANGARI'),
            (5,'ALVARO BANDEIRA','ALVARO BANDEIRA,ALVARO BANDEIRA'),
            (6,'ALVARO FERNANDO DA ROCHA MOTA','ALVARO FERNANDO DA ROCHA MOTA,ALVARO FERNANDO DA ROCHA MOTA'),
            (7,'AMAURY AUGUSTO LORDELLO','AMAURY AUGUSTO LORDELLO,AMAURY AUGUSTO LORDELLO'),
            (8,'ANTONIO CARLOS COLANGELO LUZ','ANTONIO CARLOS COLANGELO LUZ,ANTONIO CARLOS COLANGELO LUZ'),
            (9,'ANTONIO DE SOUZA CORREA MEYER','ANTONIO DE SOUZA CORREA MEYER,ANTONIO DE SOUZA CORREA MEYER'),
            (10,'ANTONIO JOSE PASCHOAL','ANTONIO JOSE PASCHOAL,ANTONIO JOSE PASCHOAL'),
            (11,'APORTE DTVM LTDA.','APORTE,APORTE DTVM LTDA.'),
            (12,'ARAUCARIA CCTVM S/A','ARAUCARIA,ARAUCARIA CCTVM S/A'),
            (13,'ARTHUR BRANDI SOBRINHO','ARTHUR BRANDI SOBRINHO,ARTHUR BRANDI SOBRINHO'),
            (14,'AUGUSTO CALMON VILLAS BOAS','AUGUSTO CALMON VILLAS BOAS,AUGUSTO CALMON VILLAS BOAS'),
            (15,'BANCO ANTONIO DE QUEIROZ S/A','BANCO ANTONIO DE QUEIROZ,BANCO ANTONIO DE QUEIROZ S/A'),
            (16,'BANCO CREDIBANCO S/A','BANCO CREDIBANCO,BANCO CREDIBANCO S/A'),
            (17,'BANCO CREDIT LYONNAIS BRASIL S/A','BANCO CREDIT LYONNAIS BRASIL,BANCO CREDIT LYONNAIS BRASIL S/A'),
            (18,'BANCO DO NORDESTE DO BRASIL S/A','BANCO DO NORDESTE DO BRASIL,BANCO DO NORDESTE DO BRASIL S/A'),
            (19,'BANCO EUROPEU PARA AMERICA LATINA S/A','BANCO EUROPEU PARA AMERICA LATINA,BANCO EUROPEU PARA AMERICA LATINA S/A'),
            (20,'BANCO LIBERAL S/A','BANCO LIBERAL,BANCO LIBERAL S/A'),
            (21,'BANCO PAULISTA S/A','BANCO PAULISTA,BANCO PAULISTA S/A'),
            (22,'BCO TRICURY S/A','BCO TRICURY,BCO TRICURY S/A'),
            (23,'BENEDITO DOURADO DA LUZ','BENEDITO DOURADO DA LUZ,BENEDITO DOURADO DA LUZ'),
            (24,'BNY MELLON SERVICOS FINANCEIROS DTVM S.A','BNY MELLON,BNY MELLON SERVICOS FINANCEIROS DTVM S.A,BNY MELLON SERVICOS FINANCEIROS DTVM S/A'),
            (25,'BRL TRUST DTVM SA','BRL TRUST,BRL TRUST DTVM SA,BRL TRUST DTVM S/A'),
            (26,'C&D DTVM SA','CD,C&D DTVM SA'),
            (27,'C. VIDIGAL & ASSOCIADOS DTVM LTDA','C VIDIGAL ASSOCIADOS,C. VIDIGAL & ASSOCIADOS DTVM LTDA'),
            (28,'CARLOS EDUARDO MOREIRA FERREIRA','CARLOS EDUARDO MOREIRA FERREIRA,CARLOS EDUARDO MOREIRA FERREIRA'),
            (29,'CARLOS ROCHA VILLELA','CARLOS ROCHA VILLELA,CARLOS ROCHA VILLELA'),
            (30,'CHECKINVEST DTVM LTDA.','CHECKINVEST,CHECKINVEST DTVM LTDA.'),
            (31,'CHENG TIA YUE','CHENG TIA YUE,CHENG TIA YUE'),
            (32,'CORRETORA GERAL DE VALORES E CAMBIO LTDA.','CORRETORA GERAL DE VALORES E CAMBIO,CORRETORA GERAL DE VALORES E CAMBIO LTDA.'),
            (33,'DATABANK CCVM LTDA.','DATABANK CCVM,DATABANK CCVM LTDA.'),
            (34,'DISTRIGOLD DTVM LTDA.','DISTRIGOLD,DISTRIGOLD DTVM LTDA.'),
            (35,'EDUARDO ANTONIO MOTTA MAY','EDUARDO ANTONIO MOTTA MAY,EDUARDO ANTONIO MOTTA MAY'),
            (36,'EDUARDO CAMILO PECHIKOSKI','EDUARDO CAMILO PECHIKOSKI,EDUARDO CAMILO PECHIKOSKI'),
            (37,'EQUIPE S/A DTVM','EQUIPE SA,EQUIPE S/A DTVM'),
            (38,'ERNANI DE PAIVA SIMOES','ERNANI DE PAIVA SIMOES,ERNANI DE PAIVA SIMOES'),
            (39,'ESCR. RUY LAGE S.C.T. LTDA.','ESCR RUY LAGE SCT,ESCR. RUY LAGE S.C.T. LTDA.'),
            (40,'EZEQUIEL DUTRA DE OLIVEIRA','EZEQUIEL DUTRA DE OLIVEIRA,EZEQUIEL DUTRA DE OLIVEIRA'),
            (41,'FAIR CCV LTDA.','FAIR CCV,FAIR CCV LTDA.'),
            (42,'FERNANDO A.A. DE OLIVEIRA','FERNANDO AA DE OLIVEIRA,FERNANDO A.A. DE OLIVEIRA'),
            (43,'FERNANDO ANTONIO AZEVEDO MARQUES PRESTES','FERNANDO ANTONIO AZEVEDO MARQUES PRESTES,FERNANDO ANTONIO AZEVEDO MARQUES PRESTES'),
            (44,'FINAXIS CTVM S.A','FINAXIS,FINAXIS CTVM S.A'),
            (45,'FOCO DTVM LTDA','FOCO,FOCO DTVM LTDA'),
            (46,'FRAM CAPITAL DTVM S/A','FRAM CAPITAL,FRAM CAPITAL DTVM S/A'),
            (47,'FRANCISCO PINHEIRO GUIMARAES NETO','FRANCISCO PINHEIRO GUIMARAES NETO,FRANCISCO PINHEIRO GUIMARAES NETO'),
            (48,'GDC PART.SERV.FIDUCIARIOS DTVM LTDA','GDC PARTSERVFIDUCIARIOS,GDC PART.SERV.FIDUCIARIOS DTVM LTDA,GDC PARTNERS SERVICOS FIDUCIARIOS,GDC PARTNERS SERVICOS FIDUCIARIOS L'),
            (49,'GDC PARTNERS SERVICOS FIDUCIARIOS DTVM','GDC PARTNERS SERVICOS FIDUCIARIOS DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIO,GDC PARTNERS SERVICOS FIDUCIARIOS DISTRIBUIDORA DE TITULOS E VALORES  MOBILIARIO,GDC PARTNERS SERVICOS FIDUCIARIOS,GDC PARTNERS SERVICOS FIDUCIARIOS DTVM,GDC PARTNERS SERVICOS FIDUCIARIOS L,GDC PARTSERVFIDUCIARIOS,GDC PARTNERS SERVICOS FIDUCIARIOS L,GDC PARTNERS SERVICOS FIDUCIARIOS,GDC PARTNERS SERVICOS FIDUCIARIOS DTVM L,GDC PARTSERVFIDUCIARIOS'),
            (50,'GERALDO CORREA CVM S/A','GERALDO CORREA CVM,GERALDO CORREA CVM S/A'),
            (51,'GERALDO ISOLDO DE MELLO CASTANHO','GERALDO ISOLDO DE MELLO CASTANHO,GERALDO ISOLDO DE MELLO CASTANHO'),
            (52,'GRADUAL CCTVM SA','GRADUAL,GRADUAL CCTVM SA'),
            (53,'GREGORIO MANCEBO RODRIGUEZ','GREGORIO MANCEBO RODRIGUEZ,GREGORIO MANCEBO RODRIGUEZ'),
            (54,'GUY DINIZ XAVIER','GUY DINIZ XAVIER,GUY DINIZ XAVIER'),
            (55,'H.COMMCOR DTVM LTDA','HCOMMCOR,H.COMMCOR DTVM LTDA'),
            (56,'HAMILTON REY ALENCASTRO','HAMILTON REY ALENCASTRO,HAMILTON REY ALENCASTRO'),
            (57,'HAROLD THAU','HAROLD THAU,HAROLD THAU'),
            (58,'HEDGING-GRIFFO CV S/A','HEDGINGGRIFFO CV,HEDGING-GRIFFO CV S/A'),
            (59,'HELIO DA SILVA CAMPOS','HELIO DA SILVA CAMPOS,HELIO DA SILVA CAMPOS'),
            (60,'INDUSVAL S/A CTVM','INDUSVAL SA,INDUSVAL S/A CTVM'),
            (61,'INTL FCSTONE DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA','INTL FCSTONE,INTL FCSTONE DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA'),
            (62,'INTL FCSTONE DTVM LTDA','INTL FCSTONE,INTL FCSTONE DTVM LTDA'),
            (63,'ISOLDI S/A CVM','ISOLDI SA CVM,ISOLDI S/A CVM'),
            (64,'JAYME VILLAS BOAS NETO','JAYME VILLAS BOAS NETO,JAYME VILLAS BOAS NETO'),
            (65,'JOAO ELIAS MOKDECI','JOAO ELIAS MOKDECI,JOAO ELIAS MOKDECI'),
            (66,'JOAO MANOEL CONRADO RIBEIRO','JOAO MANOEL CONRADO RIBEIRO,JOAO MANOEL CONRADO RIBEIRO'),
            (67,'JOHN MURRAY SUPLICY','JOHN MURRAY SUPLICY,JOHN MURRAY SUPLICY'),
            (68,'JOSE EDUARDO MENDES GONCALVES','JOSE EDUARDO MENDES GONCALVES,JOSE EDUARDO MENDES GONCALVES'),
            (69,'JOSE GOVERNO PAIS','JOSE GOVERNO PAIS,JOSE GOVERNO PAIS'),
            (70,'JOSE LUIZ SALLES FREIRE','JOSE LUIZ SALLES FREIRE,JOSE LUIZ SALLES FREIRE'),
            (71,'JOSE RUBENS CAFARELLI','JOSE RUBENS CAFARELLI,JOSE RUBENS CAFARELLI'),
            (72,'JOSE SCHMITT SILVEIRA','JOSE SCHMITT SILVEIRA,JOSE SCHMITT SILVEIRA'),
            (73,'JUAREZ CELIO DA GAMA DIAS COSTA','JUAREZ CELIO DA GAMA DIAS COSTA,JUAREZ CELIO DA GAMA DIAS COSTA'),
            (74,'LECCA DTVM LTDA.','LECCA,LECCA DTVM LTDA.'),
            (75,'LEONIDAS CARDOSO DE MENEZES','LEONIDAS CARDOSO DE MENEZES,LEONIDAS CARDOSO DE MENEZES'),
            (76,'LUIS CARLOS ECHEVERRIA PIVA','LUIS CARLOS ECHEVERRIA PIVA,LUIS CARLOS ECHEVERRIA PIVA'),
            (77,'LUIS EDUARDO DA COSTA CARVALHO','LUIS EDUARDO DA COSTA CARVALHO,LUIS EDUARDO DA COSTA CARVALHO'),
            (78,'LUIZ DA PENHA SOUZA DA SILVA','LUIZ DA PENHA SOUZA DA SILVA,LUIZ DA PENHA SOUZA DA SILVA'),
            (79,'LUIZ EDUARDO CERVASIO','LUIZ EDUARDO CERVASIO,LUIZ EDUARDO CERVASIO'),
            (80,'LUIZ FERNANDO LOPES FILHO','LUIZ FERNANDO LOPES FILHO,LUIZ FERNANDO LOPES FILHO'),
            (81,'LUIZ LEONARDO CANTIDIANO','LUIZ LEONARDO CANTIDIANO,LUIZ LEONARDO CANTIDIANO'),
            (82,'LUIZ OSCAR LOPES','LUIZ OSCAR LOPES,LUIZ OSCAR LOPES'),
            (83,'Limine Trust DTVM Ltda','LIMINE TRUST,Limine Trust DTVM Ltda'),
            (84,'MANOEL KELLER DA SILVA','MANOEL KELLER DA SILVA,MANOEL KELLER DA SILVA'),
            (85,'MARCO AURÉLIO MACHADO CARDOSO','MARCO AURELIO MACHADO CARDOSO,MARCO AURÉLIO MACHADO CARDOSO'),
            (86,'MARCOS FURKIM NETTO','MARCOS FURKIM NETTO,MARCOS FURKIM NETTO'),
            (87,'MARCOS PAULO SOUZA DANTAS FILHO','MARCOS PAULO SOUZA DANTAS FILHO,MARCOS PAULO SOUZA DANTAS FILHO'),
            (88,'MARIO SERGIO CARDIM NETO','MARIO SERGIO CARDIM NETO,MARIO SERGIO CARDIM NETO'),
            (89,'MARLIN S/A CCTVM','MARLIN SA,MARLIN S/A CCTVM'),
            (90,'MILTON OSAMU KAMITSUJ','MILTON OSAMU KAMITSUJ,MILTON OSAMU KAMITSUJ'),
            (91,'MORGAN GUARANTY TRUST COMPANY OF NY','MORGAN GUARANTY TRUST COMPANY OF NY,MORGAN GUARANTY TRUST COMPANY OF NY'),
            (92,'MUFID ADIB KFOURI','MUFID ADIB KFOURI,MUFID ADIB KFOURI'),
            (93,'Maurício da Costa Ribeiro','MAURICIO DA COSTA RIBEIRO,Maurício da Costa Ribeiro'),
            (94,'NILTON DA S. COMBRE','NILTON DA S COMBRE,NILTON DA S. COMBRE'),
            (95,'NOE DE MEDEIROS','NOE DE MEDEIROS,NOE DE MEDEIROS'),
            (96,'NOVO NORTE S/A CV','NOVO NORTE SA CV,NOVO NORTE S/A CV'),
            (97,'OLIVEIRA TRUST DTVM SA','OLIVEIRA TRUST,OLIVEIRA TRUST DTVM SA,OLIVEIRA TRUST DTVM S/A'),
            (98,'OMAR CAMARGO CCV LTDA.','OMAR CAMARGO CCV,OMAR CAMARGO CCV LTDA.,OMAR CAMARGO CCV LTDA'),
            (99,'ORLA DTVM S/A','ORLA,ORLA DTVM S/A'),
            (100,'PAULO CESAR POZO DE MATOS','PAULO CESAR POZO DE MATOS,PAULO CESAR POZO DE MATOS'),
            (101,'PEDRO LUIZ MONACO LABATE','PEDRO LUIZ MONACO LABATE,PEDRO LUIZ MONACO LABATE'),
            (102,'PEDRO ROMEIRO HERMETO','PEDRO ROMEIRO HERMETO,PEDRO ROMEIRO HERMETO'),
            (103,'PETRA PERSONAL TRADER CTVM SA','PETRA PERSONAL TRADER,PETRA PERSONAL TRADER CTVM SA,PETRA PERSONAL TRADER CTVM S/A'),
            (104,'PINTO DE ALMEIDA DTVM S/A','PINTO DE ALMEIDA,PINTO DE ALMEIDA DTVM S/A'),
            (105,'PLANNER CV SA','PLANNER CV,PLANNER CV SA,PLANNER CV S/A,PLANNER TRUSTEE,PLANNER TRUSTEE DTVM LTDA.,PLANNERSANVEST TRUSTEE,PLANNER TRUSTEE,PLANNER TRUSTEE DTVM LTDA,PLANNERSANVEST TRUSTEE,PLANNER TRUSTEE DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA,PLANNERSANVEST TRUSTEE,PLANNERSANVEST TRUSTEE,PLANNER TRUSTEE,PLANNER-SANVEST TRUSTEE DTVM LTDA.'),
            (106,'Pentágono','PENTAGONO,PENTAGONO SA,Pentágono,PENTAGONO SA DTVM,PENTAGONO S/A DTVM'),
            (107,'RAIMUNDO FRANCISCO PADILHA SAMPAIO','RAIMUNDO FRANCISCO PADILHA SAMPAIO,RAIMUNDO FRANCISCO PADILHA SAMPAIO'),
            (108,'RICARDO TEIXEIRA DE CARVALHO SOUZA','RICARDO TEIXEIRA DE CARVALHO SOUZA,RICARDO TEIXEIRA DE CARVALHO SOUZA'),
            (109,'ROBERT ALVARENGA DE SOUZA','ROBERT ALVARENGA DE SOUZA,ROBERT ALVARENGA DE SOUZA'),
            (110,'RUI JOSE VIANNA LAGE','RUI JOSE VIANNA LAGE,RUI JOSE VIANNA LAGE'),
            (111,'RUY BATISTA PEREIRA FILHO','RUY BATISTA PEREIRA FILHO,RUY BATISTA PEREIRA FILHO'),
            (112,'SABATINO AVIGDOR','SABATINO AVIGDOR,SABATINO AVIGDOR'),
            (113,'SCHAHIN CURY CCVM S/A','SCHAHIN CURY CCVM,SCHAHIN CURY CCVM S/A'),
            (114,'SENSO CCVM S/A','SENSO CCVM,SENSO CCVM S/A'),
            (115,'SERGIO BAEZ SAMPAIO','SERGIO BAEZ SAMPAIO,SERGIO BAEZ SAMPAIO'),
            (116,'SIMPLIFIC PAVARINI DTVM LTDA','SIMPLIFIC PAVARINI,SIMPLIFIC PAVARINI DTVM LTDA'),
            (117,'SLW CVC LTDA.','SLW CVC,SLW CVC LTDA.,SLW CVC LTDA'),
            (118,'STONEX DTVM LTDA','STONEX,STONEX DTVM LTDA'),
            (119,'SYLVIO RUIZ COLLE','SYLVIO RUIZ COLLE,SYLVIO RUIZ COLLE'),
            (120,'TERRA INVESTIMENTOS DTVM LTDA','TERRA INVESTIMENTOS,TERRA INVESTIMENTOS DTVM LTDA'),
            (121,'THECA CCTVM LTDA.','THECA,THECA CCTVM LTDA.'),
            (122,'THEODORO CARVALHO DE FREITAS','THEODORO CARVALHO DE FREITAS,THEODORO CARVALHO DE FREITAS'),
            (123,'TRUSTEE DTVM LTDA','TRUSTEE,TRUSTEE DTVM LTDA'),
            (124,'VLADIMIR ANTONIO RIOLI','VLADIMIR ANTONIO RIOLI,VLADIMIR A RIOLI,VLADIMIR ANTONIO RIOLI,VLADIMIR A RIOLI,VLADIMIR A. RIOLI,VLADIMIR ANTONIO RIOLI'),
            (125,'VORTX DTVM LTDA.','VORTX,VORTX DTVM LTDA.,VORTX DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.'),
            (126,'VX PAVARINI DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA','VX PAVARINI,PAVARINI,VX PAVARINI DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA,PAVARINI,PAVARINI DTVM LTDA,VX PAVARINI'),
            (127,'WILSON MUGNAINI','WILSON MUGNAINI,WILSON MUGNAINI')
        """
    )
    op.execute("select setval('icatu.agentes_fiduciarios_id_seq', 127)")

    op.execute("ALTER TABLE icatu.ativos ADD quantidade_mercado int8 NULL")
    op.execute("ALTER TABLE icatu.ativos ADD agente_fiduciario_id int4 NULL")
    op.execute(
        "alter table icatu.ativos add CONSTRAINT ativos_agente_fiduciario_id_fkey FOREIGN KEY (agente_fiduciario_id) REFERENCES icatu.agentes_fiduciarios(id) on update cascade"
    )

    op.execute("create schema arquivos")
    op.execute(
        """
        create table arquivos.ativos_notion (
            ativo_codigo varchar(11) PRIMARY KEY ,
            notion_id text NOT null unique,
            CONSTRAINT ativos_notion_ativo_codigo_fkey FOREIGN KEY (ativo_codigo) REFERENCES icatu.ativos(codigo)
        )
        """
    )


def downgrade() -> None:
    op.execute("drop table arquivos.ativos_notion")
    op.execute("drop schema arquivos")

    op.execute(
        "alter table icatu.ativos drop CONSTRAINT ativos_agente_fiduciario_id_fkey"
    )
    op.execute("alter table icatu.ativos drop column agente_fiduciario_id")
    op.execute("alter table icatu.ativos drop column quantidade_mercado")

    op.execute("drop table icatu.agentes_fiduciarios")
