"""data_de_inicio_e_rentabilidades_cotas_patrimonio_liquido

Revision ID: 03e0cde5d901
Revises: 20240614132259
Create Date: 2024-07-25 09:50:08.864333

"""

from typing import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "03e0cde5d901"
down_revision: str | None = "20240614132259"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        INSERT INTO icatu.indices_benchmark (nome) VALUES
            ('IBrX'),
            ('Ibovespa'),
            ('Selic'),
            ('IMA-B')
        """
    )
    op.execute("ALTER TABLE icatu.fundos ADD COLUMN data_inicio DATE")

    op.execute(
        """
        CREATE TABLE icatu.fundo_cotas_rentabilidades (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            data_posicao Date NOT NULL,
            preco_cota FLOAT,
            rentabilidade_dia FLOAT,
            rentabilidade_mes FLOAT,
            rentabilidade_ano FLOAT,
            rentabilidade_12meses FLOAT,
            rentabilidade_24meses FLOAT,
            rentabilidade_36meses FLOAT,
            
            fundo_id INT NOT NULL,
            CONSTRAINT fundo_cotas_rentabilidades_fundo FOREIGN KEY (fundo_id) REFERENCES icatu.fundos(id) ON DELETE CASCADE ON UPDATE CASCADE
        )
        """
    )

    op.execute(
        """
        CREATE TABLE icatu.fundo_patrimonio_liquido_rentabilidades (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            data_posicao Date NOT NULL,
            patrimonio_liquido FLOAT,
            media_12meses FLOAT,
            media_24meses FLOAT,
            media_36meses FLOAT,
            rentabilidade_dia FLOAT,
            rentabilidade_mes FLOAT,
            rentabilidade_ano FLOAT,
            rentabilidade_12meses FLOAT,
            rentabilidade_24meses FLOAT,
            rentabilidade_36meses FLOAT,
            
            fundo_id INT NOT NULL,
            CONSTRAINT fundo_patrimonio_liquido_rentabilidades_fundo FOREIGN KEY (fundo_id) REFERENCES icatu.fundos(id) ON DELETE CASCADE ON UPDATE CASCADE
        )
        """
    )

    op.execute(
        """
        CREATE TABLE icatu.indice_benchmark_rentabilidades (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            data_posicao Date NOT NULL,
            rentabilidade_dia FLOAT,
            rentabilidade_mes FLOAT,
            rentabilidade_ano FLOAT,
            rentabilidade_12meses FLOAT,
            rentabilidade_24meses FLOAT,
            rentabilidade_36meses FLOAT,
            
            indice_benchmark_id INT NOT NULL,
            CONSTRAINT indice_benchmark_rentabilidades_indice_benchmark FOREIGN KEY (indice_benchmark_id) REFERENCES icatu.indices_benchmark(id) ON DELETE CASCADE ON UPDATE CASCADE
        )
        """
    )


def downgrade() -> None:
    op.execute("DELETE FROM icatu.indices_benchmark WHERE nome = 'IBrX'")
    op.execute("DELETE FROM icatu.indices_benchmark WHERE nome = 'Ibovespa'")
    op.execute("DELETE FROM icatu.indices_benchmark WHERE nome = 'Selic'")
    op.execute("DELETE FROM icatu.indices_benchmark WHERE nome = 'IMA-B'")

    op.execute("ALTER TABLE icatu.fundos DROP COLUMN data_inicio CASCADE")
    op.execute("DROP TABLE icatu.fundo_cotas_rentabilidades CASCADE")
    op.execute("DROP TABLE icatu.indice_benchmark_rentabilidades CASCADE")
    op.execute("DROP TABLE icatu.fundo_patrimonio_liquido_rentabilidades CASCADE")
