FROM crvanguarda.azurecr.io/iv-front-sistema-v2-lib:latest

WORKDIR /home/node

USER root

RUN chown -R node /home/node

# https://learn.microsoft.com/en-us/azure/app-service/configure-custom-container?tabs=debian&pivots=container-linux#enable-ssh
RUN apt-get update \
    && apt-get install -y --fix-missing --fix-broken --no-install-recommends dialog \
    && apt-get install -y --fix-missing --fix-broken --no-install-recommends openssh-server \
    && echo "root:Docker!" | chpasswd

COPY application/sshd_config /etc/ssh

USER node

ENV TZ='America/Sao_Paulo'

RUN mv /tmp/node/node_modules .
COPY application/app ./app
COPY application/lib ./lib
COPY application/public ./public

COPY application/middleware.ts .
COPY application/next.config.js .
COPY application/package.json .
COPY application/tsconfig.json .

ENV NEXT_PUBLIC_IV_API_URL='https://app-vanguarda-back-fastapi-prd.azurewebsites.net'
ENV NEXT_PUBLIC_WS_URL='wss://app-vanguarda-back-fastapi-prd.azurewebsites.net/ws'

RUN npm run build

COPY application/entrypoint.sh .

USER root

EXPOSE 2222

ENTRYPOINT ./entrypoint.sh
