FROM python:3.13.4-bullseye

WORKDIR /tmp/python

USER root

RUN addgroup --gid 1000 host_group; \
    adduser --disabled-password --gecos 'Host User' --uid 1000 --ingroup host_group host_user;
RUN chown -R host_user /tmp/python

ENV HOME="/home/host_user"
USER host_user

RUN mkdir /home/host_user/.cache

COPY requirements.txt .
RUN pip install --target=./site-packages -U -r requirements.txt

USER root

RUN PYTHONPATH="/tmp/python/site-packages" python -m playwright install chromium --with-deps
RUN chown -R host_user /home/host_user/.cache/ms-playwright

USER host_user